name: deploy-lesspass-fingerprint-package

on:
  push:
    paths:
      - "packages/lesspass-fingerprint/**"

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: test lesspass-fingerprint package
        run: |
          cd packages/lesspass-fingerprint
          yarn install
          yarn test

  deploy:
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: deploy lesspass-fingerprint package
        run: |
          cd packages
          ./deploy lesspass-fingerprint
        continue-on-error: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
